trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'
    
    - script: |
        npm install
        npm run build
      displayName: 'Build frontend'
    
    - task: Maven@3
      inputs:
        mavenPomFile: 'backend/pom.xml'
        goals: 'clean package'
      displayName: 'Build backend'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: '<Azure-Subscription-Name>'
        appType: 'webApp'
        appName: '<Your-Frontend-App-Name>'
        package: '$(System.DefaultWorkingDirectory)/frontend/build'
      displayName: 'Deploy frontend'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: '<Azure-Subscription-Name>'
        appType: 'webApp'
        appName: '<Your-Backend-App-Name>'
        package: '$(System.DefaultWorkingDirectory)/backend/target/*.jar'
      displayName: 'Deploy backend'
