trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: EventManagerSecrets

stages:
  - stage: Build
    jobs:
      - job: BuildFrontend
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "14.x"
            displayName: "Install Node.js"

          - script: |
              cd frontend
              npm install
              npm run build
            displayName: "Build frontend"

      - job: BuildBackend
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: "backend/pom.xml"
              goals: "clean package"
            displayName: "Build backend"

  - stage: Deploy
    jobs:
      - job: DeployFrontend
        steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: "AzureSubscription1"
              appType: "webApp"
              appName: "event-manager-frontend"
              package: "$(System.DefaultWorkingDirectory)/frontend/build"
            displayName: "Deploy frontend"

      - job: DeployBackend
        steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: "AzureSubscription1"
              appType: "webApp"
              appName: "event-manager-backend"
              package: "$(System.DefaultWorkingDirectory)/backend/target/*.jar"
            displayName: "Deploy backend"
          - script: echo "Setting environment variables for the backend app"
            displayName: "Set Backend Environment Variables"
            env:
              MONGODB_CONNECTION_STRING: $(MONGODB_CONNECTION_STRING)
          - task: AzureWebApp@1
            inputs:
              azureSubscription: "AzureSubscription1"
              appType: "webApp"
              appName: "event-manager-backend"
              appSettings: |
                MONGODB_CONNECTION_STRING=$(MONGODB_CONNECTION_STRING)
            displayName: "Deploy backend"
