trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: EventManagerSecrets

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "14.x"
            displayName: "Install Node.js"

          - script: |
              cd frontend
              npm install
              npm run build
            displayName: "Build frontend"

          - task: Maven@3
            inputs:
              mavenPomFile: "backend/pom.xml"
              goals: "clean package"
            displayName: "Build backend"

  - stage: Deploy
    jobs:
      - job: DeployFrontend
        steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: "Azure subscription 1"
              appType: "webApp"
              appName: "event-manager-frontend"
              package: "$(System.DefaultWorkingDirectory)/frontend/build"
            displayName: "Deploy frontend"

      - job: DeployBackend
        steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: "Azure subscription 1"
              appType: "webApp"
              appName: "event-manager-backend"
              package: "$(System.DefaultWorkingDirectory)/backend/target/*.jar"
              appSettings:
                - name: MONGODB_CONNECTION_STRING
                  value: $(MONGODB_CONNECTION_STRING)
            displayName: "Deploy backend"
