pipeline {
    agent any

    stages {
        stage('Build Frontend') {
            steps {
                script {
                    docker.image('node:14').inside {
                        sh 'npm install'
                        sh 'npm run build'
                    }
                }
            }
        }
        stage('Build Backend') {
            steps {
                script {
                    docker.image('maven:3.8.1-jdk-11').inside {
                        sh 'mvn clean package -f backend/pom.xml'
                    }
                }
            }
        }
    }
}
